### ISSUE TITLE
bolt stopped/quitted after `fail` a tup

### ISSUE THREAD

**Issue by imcom** [Yelp/pyleus#141]
I am testing the exclamation_bolt but with a little modification like below:

I added a bolt after the existing one, and it will fail the tup depending on the work length

```
if len(tup.values[0]) % 2 == 0:
            log.debug('try to fail tup and see what\'s happening')
            self.fail(tup)

        word = tup.values[0] + "+++"
```

What I've been observing is that when the fail fired, bolt continued with the rest of code and afterwards it was just vanished or stopped. I would never see the second bolt running again.

here is the yaml definition:

```
topology:

    - spout:
        name: words
        module: exclamation_topology.test_word_spout
        parallelism_hint: 1

    - bolt:
        name: exclaim1
        module: exclamation_topology.exclamation_bolt
        parallelism_hint: 1
        groupings:
            - shuffle_grouping: words

    - bolt:
        name: exclaim2
        module: exclamation_topology.random_fail_bolt
        parallelism_hint: 1
        groupings:
            - shuffle_grouping: exclaim1

```

Either I get the fail mechanism all wrong or this is a critical bug in pyleus ... please help me to work it out.

Thanks in advance
