### ISSUE TITLE
Is it possible that one spout subscribes multiple topics from kafka

### ISSUE THREAD

**Issue by meowoodie** [Yelp/pyleus#161]
I have a question that is it possible that one spout subscribes multiple topics from kafka.
For an instance, a spout named "test_spout" receives streaming data from two topics in kafka.
The yaml file may looks like this:

``` yaml
topology:
    - spout:
        name: kafka_user_raw_data
        type: kafka
        options:
            #module: streaming_topology.user_behavior_spout
            # The Kafka topic to stream from.
            # Required.
            topic:
              - topic1
              - topic2
```

But it couldn't work. Could you please tell me how to achieve this?
