### ISSUE TITLE
How to define global options in "pyleus_topology.yaml" for all components?

### ISSUE THREAD

**Issue by arnolddeng85** [Yelp/pyleus#163]
I want to define DB server info(host, port, etc.) which are used by all the spouts and bolts. But I think it is hard to maintain if I define the same DB server info at the options under all the components on "pyleus_topology.yaml". Such as:

``` yaml
    - spout:
        options:
               host: 192.168.0.1
               port: 3306
    - bolt:
        options:
               host: 192.168.0.1
               port: 3306
    - bolt:
        options:
               host: 192.168.0.1
               port: 3306
```

So how to define global options in "pyleus_topology.yaml" for all components and how to get the global options at component class code?
